### ISSUE TITLE
Netlify deploy is broken

### ISSUE THREAD

**Issue by alexgibson** [mozmeao/performance-dashboard#12]
See: https://ci.us-west.moz.works/view/Bedrock/job/performance-dashboard/280/console

```
Warning: -t is not a netlify command
```

It looks like there was a Netlify CLI update to 2.0 that changed the way tokens and site ID's are handled. There's also a fix here for some regressions that is due to be released some time today: https://github.com/netlify/cli/pull/147

/cc @pmac

**Comment by pmac** [comment]
@alexgibson PR filed

**Comment by bcomnes** [comment]
Apologies to cause a disturbance.  I'm releasing the auth token flow as flag today

https://github.com/netlify/cli/pull/147

**Comment by alexgibson** [comment]
@bcomnes no worries, thanks for being diligent checking in here 💯

**Comment by pmac** [comment]
It's on us (read: me) really for failing to pin a version in our netlify-cli install... I should add a PR to do that.

**Comment by alexgibson** [comment]
Looks like something is still not quite right:

```
TypeError: Path must be a string. Received null
    at findProjectRoot (/usr/local/lib/node_modules/netlify-cli/src/base/utils/projectRoot.js:15:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/netlify-cli/src/base/utils/projectRoot.js:19:14)
Build step 'Execute shell' marked build as failure
```

**Comment by bcomnes** [comment]
I released https://github.com/netlify/cli/releases/tag/v2.1.1 that should address that specific problem.  Do you know what version threw that?
