### ISSUE TITLE
Circle build and Netlify deployment

### ISSUE THREAD

**Issue by pmac** [mozmeao/performance-dashboard#2]
Excellent work on this @alexgibson 🎉 I've taken the liberty of forking it and setting up some CI and hosting for it. If you look at [my fork](https://github.com/pmac/performance-dashboard) you'll see in the last few commits to my master branch I've added CircleCI config for building (and building nightly) and [deployment to Netlify](http://mozmeao-perf-dashboard.netlify.com/). I couldn't use Netlify to build directly as their build image doesn't include browsers. Let me know if you like it and I'll submit a PR here and get things setup. If the Netlify bit isn't necessary it's easy enough to do Github pages instead.

**Comment by alexgibson** [comment]
Thanks @pmac this looks great!

I'm still figuring out a couple more features before I'm ready to automate. One such feature is keeping a trend of the scores for each page over time, so that we can have a fancy graph of sorts for each page. To do this, it may mean we need to store that data somewhere, where it can be read & updated each time the app runs. Any thoughts you have here would be great?

One issue I do notice here, looking at the [netlify dashboardd](http://mozmeao-perf-dashboard.netlify.com/), is that performance scores are quite a bit lower than when I run them on my machine. I see a lot of `Your page took too long to load.` in the reports, which leads me to believe the network conditions in CircleCI may not be all that great. Is there anything that can be improved here?

**Comment by pmac** [comment]
> I'm still figuring out a couple more features before I'm ready to automate. One such feature is keeping a trend of the scores over time, so that we can have a fancy graph of sorts for each page. To do this, it may mean we need to store that data somewhere (as JSON), where it can be read & updated each time the app runs. Any thoughts you have here would be great?

Hmm... yeah. That might be a challenge. I'll think about that. Perhaps sending metrics to DataDog for every build could help with this...

> One other issue I do notice here, looking at the netlify dashboard, is that performance scores are quite a bit lower than when I run them on my machine. I see a lot of Your page took too long to load. in the reports, which leads me to believe the network conditions in CircleCI may not be all that great. Is there anything that can be improved here, or any other options that we could try?

Interesting. This may not be solvable when using any 3rd party service. It wouldn't be hard to switch to using Jenkins for CI though, and that should remove network issues from the equation since they'll be in the same cluster of servers. The risk with Jenkins is that the numbers might appear better than reality, but for checking page weight and the rest it should work great. I can work on doing that soon if you like.

**Comment by alexgibson** [comment]
> Interesting. This may not be solvable when using any 3rd party service. It wouldn't be hard to switch to using Jenkins for CI though, and that should remove network issues from the equation since they'll be in the same cluster of servers. The risk with Jenkins is that the numbers might appear better than reality, but for checking page weight and the rest it should work great. I can work on doing that soon if you like.

If you have some time to look into that, it would be much appreciated 👍

**Comment by alexgibson** [comment]
> Hmm... yeah. That might be a challenge. I'll think about that. Perhaps sending metrics to DataDog for every build could help with this...

To be clear, this is a stretch goal and maybe something we can work toward. I'd say the initial thing would be to get this deploying somewhere with reliable test runs. I appreciate you taking the initiative here Paul, thanks for the assist!

**Comment by pmac** [comment]
Any time! Thank YOU for the initiative for getting something like this started. It's looking great 🎉 

I've moved it to [Jenkins](https://ci.us-west.moz.works/view/Bedrock/job/performance-dashboard/), but it still looks like the results aren't great perf wise. [Take a look](https://mozmeao-perf-dashboard.netlify.com/) and let me know if you think things have improved. It could be that running the tests via Docker just isn't very performant...

**Comment by alexgibson** [comment]
> It could be that running the tests via Docker just isn't very performant...

Hmm yeah :/ I wonder are there any other options to run this in an automated way without docker? I guess for now I can run them manually and then push to a branch that we could deploy, at least until we can figure this out?

**Comment by alexgibson** [comment]
Or alternatively, just a command script that can be run to deploy the /dashboard folder to netlify?

**Comment by pmac** [comment]
Yup. You can `npm install -g netlify-cli` and then `netlify deploy` and it'll deploy for you. I may be able to give you access to deploy to the netlify app I setup, or you can setup your own easily enough.

**Comment by alexgibson** [comment]
I’ll sign up and see if I can figure it out 👍

**Comment by alexgibson** [comment]
Thinking about this further, I may to choose to go for GitHub pages for this (at least for now). It has the added benefit of all past reports being recorded in Git history, and will also make keeping track of trend data easier easier over time, without any complicated storage setup.

**Comment by alexgibson** [comment]
Just to update here - I think I have a solution to the issues we we're seeing in Docker. It's now possible to run Lighthouse reports via WebPageTest, so I'm working on switching to using the latter API as a report runner. This will also give us the benefit of even richer data, by combining the two services.

**Comment by alexgibson** [comment]
@pmac I now have this running using WebPageTest, which you can see here: https://mozmeao.github.io/performance-dashboard/

I think this should now be easier to auto build & deploy? You'll need a WebPageTest API key, which you can [get here](https://www.webpagetest.org/getkey.php). I updated the readme with instructions for how to run the script. Any questions please let me know :)

**Comment by pmac** [comment]
I've updated the Jenkins job and the docker container to use your new WPT-based version and it's working!

http://mozmeao-perf-dashboard.netlify.com/

I'll get a PR together to add the extra stuff to the primary repo.
