### ISSUE TITLE
Storage for page reports and trends data

### ISSUE THREAD

**Issue by alexgibson** [mozmeao/performance-dashboard#4]
The current version of the dashboard now updates daily, but I would love it if we could keep track of data trends over time, so that we could plot fancy graphs and look back at past reports in detail if needed.

As part of the [report creation process](https://github.com/mozmeao/performance-dashboard/blob/master/lib/trends.js#L20-L38), we currently store a `trends.json` file for each page report to the local file system (e.g. https://mozmeao-perf-dashboard.netlify.com/data/trends/www_mozilla_org/www_mozilla_org_en-US_.trend.json), as well as the full reports.

What I would like to be able to do is store these files online somewhere as part of the build process, so that we can read/write to them and update data over time. I'm not sure of the best solution here, but that's where I'm hoping this discussion can present some possible options.

**Comment by metadave** [comment]
[S3](https://aws.amazon.com/s3/) might be the best solution here. We can create a public bucket with creds for uploading files from Jenkins (or however you want to handle it). You can maintain whatever directory structure you want, and [versioning](https://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html) could be enabled. S3 buckets are cheap and easy to create.

Interacting with S3 can be done via the [AWS CLI](https://aws.amazon.com/cli/) or by any of the [AWS SDKs](https://aws.amazon.com/tools/).

**Comment by alexgibson** [comment]
I see there's a Node SDK for this, and the example looks pretty straight forward: https://github.com/aws-samples/aws-nodejs-sample

I do wonder however if uploading to s3 might be a better job for Jenkins, since that's something we'd want to happen in automation, but not necessarily when running locally in dev. I'd also like to keep the requirements for running this locally as simple as possible, so splitting out this dependency may be worthwhile.

I think the only files we'd need uploaded are the ones under `dashboard/data/trends/`, and these could be over-written each time (I don't think we'd need versioning as such, as I could `fetch` the existing JSON after each test run before appending the new data locally).

**Comment by alexgibson** [comment]
Reading up on [versioning](https://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html), it does sound useful if we enabled this either way (just to protect against accidental overwrite or deletion if nothing else).

**Comment by metadave** [comment]
We sync [viewsource to S3 from Jenkins](https://github.com/mdn/viewsourceconf/blob/master/Jenkinsfile#L21), it's usually a one-liner via the aws cli.

**Comment by metadave** [comment]
Also, would you want a nice `foo.mozilla.net` domain, or can a `foo.moz.works` domain work for you? I'm guessing that traffic will be low to these files, so we probably don't need a CDN and can serve right out of a bucket. 

I should also mention that we're looking at [Google Firebase](https://firebase.google.com/docs/hosting/) and [Netlify](https://www.netlify.com/) for static site hosting. However,  it seems to me like an S3 bucket would be fine.

**Comment by metadave** [comment]
Also, would you want a nice `foo.mozilla.net` domain, or can a `foo.moz.works` domain work for you? I'm guessing that traffic will be low to these files, so we probably don't need a CDN and can serve right out of a bucket. 

I should also mention that we're looking at [Google Firebase](https://firebase.google.com/docs/hosting/) and [Netlify](https://www.netlify.com/) for static site hosting. However,  it seems to me like an S3 bucket would be fine.

**Comment by alexgibson** [comment]
> Also, would you want a nice foo.mozilla.net domain, or can a foo.moz.works domain work for you? I'm guessing that traffic will be low to these files, so we probably don't need a CDN and can serve right out of a bucket.

A `foo.moz.works` domain should work just fine if that's easier.

> I should also mention that we're looking at Google Firebase and Netlify for static site hosting. However, it seems to me like an S3 bucket would be fine.

We're already hosting the dashboard for this on [Netlify](https://mozmeao-perf-dashboard.netlify.com/), if that has any bearing in a choice here. I'm happy to go with either that or S3.

**Comment by alexgibson** [comment]
> We're already hosting the dashboard for this on Netlify, if that has any bearing in a choice here. I'm happy to go with either that or S3.

Hmm, wait - perhaps this is even simpler. We wouldn't have anything fancy like versioning, but I could just read the JSON directly from the URL on `https://mozmeao-perf-dashboard.netlify.com/`...

**Comment by metadave** [comment]
@alexgibson +1, seems easier! I was going to ask what's preventing us from just using netlify.

**Comment by alexgibson** [comment]
> I was going to ask what's preventing us from just using netlify.

I'll see how this plays out. I was likely over-thinking it when it came to more persistent storage of the data. I don't see why using Netlify wouldn't work, we may just lose some of the extra bells & whistles S3 would provide. But this isn't exactly a critical project in terms of data history either, this may well be sufficient. I'll try out just using Netlify and report back here if I think it's not enough 👍

**Comment by alexgibson** [comment]
Implemented this in https://github.com/mozmeao/performance-dashboard/commit/afe320b14fd3f11acac60bf54f60d61b67b7da72

Will see how it runs over the next few days before closing this out. Thanks for the discussion!

**Comment by alexgibson** [comment]
This seems to be performing well enough. Closing!
