### ISSUE TITLE
What to do with this repo?

### ISSUE THREAD

**Issue by alexgibson** [mozmeao/performance-dashboard#41]
It appears that [WebPageTest](https://webpagetest.org/) is now officially owned by a company called Catchpoint. I recently received an email saying that our API key is going to be deprecated on May 3, 2021. Looking at the new [subscription plans](https://www.product.webpagetest.org/api#Pricing), there's no mention of a free/open source tier for low usage projects like this.

So the questions stands, what should we do with this repo? This was very much a hack project when I made it, and it's something I've struggled to give enough time and attention to since then. I use the dashboard to check how things are doing every so often, but I don't know if anyone else on the team really uses it much (?). With that in mind, I think we could consider retiring this?

For www, I'd like to persue capturing more real-user performance metrics, for example by adding [Core Web Vitals](https://github.com/mozilla/bedrock/issues/9680) data in our analytics.

**Comment by pmac** [comment]
+1 from me for retiring this and doing something better for WMO. It'd be nice to keep it, but if it's not providing enough value for us to pay for the service then I think retirement seems appropriate. If we do think it's worth paying for I can look into making that happen.

**Comment by stephaniehobson** [comment]
I've been using it but moving to a different tool would be fine. I have no concerns about losing the historical data.

**Comment by alexgibson** [comment]
Ok, then I think we should decomission this and archive the repo.

@pmac can you cancel the CI job that builds the site? (not 100% sure where that lives today?)

**Comment by pmac** [comment]
I'll look into that

**Comment by pmac** [comment]
It's all in GitLab. I can delete that project. Cool with everyone?

**Comment by alexgibson** [comment]
Ok by me 👍

**Comment by pmac** [comment]
Deleted. We should now be able to archive this repo.

**Comment by alexgibson** [comment]
Thanks, closing and will archive.
