### ISSUE TITLE
Jest: Test failing with latest master

### ISSUE THREAD

**Issue by schalkneethling** [mozmeao/performance-dashboard#5]
FAIL  tests/summary.test.js
  ● getReportDate

    expect(received).toEqual(expected)

    Expected value to equal:
      "2018-02-27T11:34"
    Received:
      "2018-02-27T13:34"

      13 |
      14 | test('getReportDate', () => {
    > 15 |     expect(summary.getReportDate(1519731247822)).toEqual('2018-02-27T11:34');
      16 |     expect(summary.getReportDate(1521018106766)).toEqual('2018-03-14T09:01');
      17 | });
      18 |

      at Object.<anonymous>.test (tests/summary.test.js:15:50)

**Comment by schalkneethling** [comment]
That is odd. Now that I look at it again, I cannot see a difference between those two values :-/

**Comment by schalkneethling** [comment]
Nope, there is a difference ;) PR coming up.

**Comment by alexgibson** [comment]
I can't reproduce this failure locally in master, and Travis seems happy too?
